name: Backup API Management contents 

on:
  workflow_dispatch:
    inputs:
      targetEnvironment:
        type: environment

permissions:
  id-token: write
  contents: read
  
jobs:
  backup-apim-devenv:
    runs-on: ubuntu-latest
    environment: dev
    env:
      PARAMETER_FILE: "armdeploy.${{ github.event.inputs.targetEnvironment }}.parameters.json"
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          enable-AzPSSession: true
      - name: 'Backup API Management contents'
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $devparam = Get-Content $env:PARAMETER_FILE | ConvertFrom-Json 
            $devStrAccName = $devparam.parameters.storageAccountName.value
            $bakContainer = $devparam.parameters.backupContainerName.value
            $devApimName = $devparam.parameters.apimServiceName.value
            .\ops-apim.ps1 -backup -storageAccountName $devStrAccName -containerName $bakContainer -sourceapim $devApimName
          azPSVersion: "latest"
