name: Backup API Management contents 

on:
  workflow_dispatch:
    inputs:
      apiManagement:
        type: string
        default: demo-apim-dev
      storageAccount:
        type: string
        default: demoapimdevstr
      storageContainer:
        type: string
        default: apim-backup

permissions:
  id-token: write
  contents: read
  
jobs:
  backup-apim-devenv:
    runs-on: ubuntu-latest
    environment: dev
    env:
      TARGET_APIMAN: ${{ github.event.inputs.apiManagement }}
      TARGET_STRACCOUNT: ${{ github.event.inputs.storageAccount }}
      TARGET_CONTAINER: ${{ github.event.inputs.storageContainer }}
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          enable-AzPSSession: true
      - name: 'Backup API Management contents'
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $blobfile = "{0}_{1:yyyy-MM-dd-HH-mm-ss}.apimbackup" -f $env:TARGET_APIMAN, [DateTime]::UtcNow
            Write-host ("Backup API Management {0} to https://{1}.blob.core.windows.net/{2}/{3}" -f $env:TARGET_APIMAN, $env:TARGET_STRACCOUNT, $env:TARGET_CONTAINER, $blobfile)

            $bakstr = (Get-AzStorageAccount | where { $_.StorageAccountName -eq $env:TARGET_STRACCOUNT })[0]
            $strkey = (Get-AzStorageAccountKey -ResourceGroupName $bakstr.ResourceGroupName -AccountName $bakstr.StorageAccountName)[0].Value
            $strctx = New-AzStorageContext -StorageAccountName $env:TARGET_STRACCOUNT -StorageAccountKey $strkey
            $apiman = (Get-AzApiManagement | where {$_.Name -eq $env:TARGET_APIMAN})[0]
            Backup-AzApiManagement -ResourceGroupName $apiman.ResourceGroupName -Name $apiman.Name `
              -StorageContext $strctx -TargetContainerName  $env:TARGET_CONTAINER -TargetBlobName $blobfile
          azPSVersion: "latest"
